#!/bin/bash

set -xe

# update system first thing
sudo dnf update -y

# install nix
PROFILE=~/.nix-profile/etc/profile.d/nix.sh
test -e $PROFILE && . ~/.nix-profile/etc/profile.d/nix.sh
if ! command -v nix >/dev/null 2>&1; then
  # Install
  sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
  bash <(curl -L https://nixos.org/nix/install) --daemon --yes

  # Make sure daemon is running
  sudo systemctl enable nix-daemon
  sudo systemctl start nix-daemon

  . $PROFILE
fi
mkdir -p ~/.config/nix && echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf

sudo cp /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
echo "export NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" >> ~/.bashrc

# fetch my nix flake
sudo dnf install -y git make
mkdir -p ~/src
([ -e ~/src/nix ] || true) && rm -rf ~/src/nix
git clone https://github.com/booxter/nix.git ~/src/nix

# install home-manager config
pushd ~/src/nix && make home-switch-nvcloud && popd

# switch default shell to zsh; this is awkward but works
# idea from https://discourse.nixos.org/t/unable-to-set-or-use-zsh-shell-from-standalone-home-manager-using-flakes/29269/3
echo "exec zsh" >> ~/.bash_profile # bash
echo "exec zsh" >> ~/.login # csh

sudo rm -f /etc/ssh/ssh_config.d/10-nixpkgs-support.conf
echo Match all | sudo tee /etc/ssh/ssh_config.d/10-nixpkgs-support.conf
echo IgnoreUnknown "rsaminsize,gssapikexalgorithms" | sudo tee -a /etc/ssh/ssh_config.d/10-nixpkgs-support.conf

echo 'DONE! Rebooting...'

sudo reboot
