#!/usr/bin/env bash

set -xeuo pipefail

# fetch my nix flake
sudo dnf install -y git make
mkdir -p ~/src
([ -e ~/src/nix ] || true) && rm -rf ~/src/nix
git clone https://github.com/booxter/nix.git ~/src/nix

# install home-manager config
pushd ~/src/nix && make home-switch-nvcloud && popd

# switch default shell to zsh; this is awkward but works
# idea from https://discourse.nixos.org/t/unable-to-set-or-use-zsh-shell-from-standalone-home-manager-using-flakes/29269/3
echo "exec zsh" >> ~/.bash_profile # bash
echo "exec zsh" >> ~/.login # csh

sudo rm -f /etc/ssh/ssh_config.d/10-nixpkgs-support.conf
echo Match all | sudo tee /etc/ssh/ssh_config.d/10-nixpkgs-support.conf
echo IgnoreUnknown "rsaminsize,gssapikexalgorithms" | sudo tee -a /etc/ssh/ssh_config.d/10-nixpkgs-support.conf

echo 'DONE! Rebooting...'

sudo reboot
