#!/bin/bash

ssh="$HOME/.priv-bin/cloud ssh"

# install nix
$ssh 'sudo install -d -m755 -o $(id -u) -g $(id -g) /nix'
$ssh 'curl -L https://nixos.org/nix/install | sh'

# fetch my nix flake
$ssh 'sudo dnf install -y git make'
$ssh 'mkdir -p ~/src'
$ssh 'rm -r ~/src/nix'
$ssh 'git clone https://github.com/booxter/nix.git ~/src/nix'

# install home-manager config
$ssh 'bash -l -c "cd ~/src/nix && make home-switch"'

# switch default shell to zsh; this is awkward but works
# idea from https://discourse.nixos.org/t/unable-to-set-or-use-zsh-shell-from-standalone-home-manager-using-flakes/29269/3
$ssh 'echo "exec zsh" >> ~/.bash_profile'

echo 'DONE!'
