#!/usr/bin/env bash

set -euo pipefail

# source file from the running script dir
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$SCRIPTDIR/kind-common-vars"

for node in $(kind get nodes --name "$CLUSTER_NAME"); do
	# Clean cri storage
	echo $node
  docker exec "$node" crictl rmi --prune
done
