#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Usage: $0 <hostname>"
	exit 1
fi

HOSTNAME="$1"
DNS_SERVER=192.168.1.1

IP=$(dig +short "$HOSTNAME" @"$DNS_SERVER" | head -n1)

if [ -n "$IP" ]; then
	echo "Connecting to $IP..."
	ssh -o 'SetEnv TERM=xterm-256color' -t "$IP"
	exit 0
else
	echo "No IP address found for $HOSTNAME"
	exit 1
fi
