#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Usage: $0 <hostname>"
	exit 1
fi

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
source "$SCRIPT_DIR/functions-common"

HOSTNAME="$1"

IP=$(get_local_ip "$HOSTNAME")

if [ -n "$IP" ]; then
	echo "Connecting to $IP..."
	ssh -o 'SetEnv TERM=xterm-256color' -t "$IP"
	exit 0
else
	echo "No IP address found for $HOSTNAME"
	exit 1
fi
