#!/bin/sh

set -xe

FILENAME=$(date +%Y-W%W).pdf
ABSNAME=~/$FILENAME

FROMADDR=ihrachys@redhat.com

ADDRESSEES="dalvarez bcafarel"

function join_company {
	echo $ADDRESSEES | sed "s/ /@$1 /g; s/$/@$1/"
}

TOADDRS=$(join_company redhat.com)

if ! [ -f $ABSNAME ]; then
	echo "No report file $ABSNAME found. Weekly status email not sent!" >&2
	exit 1
fi

mailsend-go -from $FROMADDR -t $TOADDRS -sub "Weekly status" \
	-use gmail auth -user $FROMADDR -pass $(pass rh/google.com) \
	body -msg "Attached.$* Cheers." attach -file $ABSNAME -name Ihar-$FILENAME
