#!/bin/sh

set -xe

# Default week offset is 0 (current week)
WEEK_OFFSET=0

# Parse options
while [ "$#" -gt 0 ]; do
  case "$1" in
    --prev)
      WEEK_OFFSET=-1
      shift
      ;;
    *)
      break
      ;;
  esac
done

# Calculate the filename based on the offset
FILENAME=$(date -d "$WEEK_OFFSET week" +%Y-W%W).pdf

ABSNAME=~/$FILENAME

FROMADDR=ihrachys@redhat.com

ADDRESSEES="dalvarez bcafarel"

function join_company {
  echo $ADDRESSEES | sed "s/ /@$1 /g; s/$/@$1/; s/ /,/g"
}

TOADDRS=$(join_company redhat.com)

if ! [ -f $ABSNAME ]; then
  echo "No report file $ABSNAME found. Weekly status email not sent!" >&2
  exit 1
fi

# Calculate final message body; if additional arguments were passed, inject as
# an additional commentary; otherwise, just send a boilerplate.
MSG="Attached."
if [ "$#" -gt 0 ]; then
  MSG="${MSG}\n\n---\n\n$*\n\n---"
fi
MSG="${MSG}\n\nCheers!"

mailsend-go -from $FROMADDR -t $TOADDRS -sub "Weekly status" \
  -use gmail auth -user $FROMADDR -pass $(pass rh/google.com) \
  body -msg "$MSG" attach -file $ABSNAME -name Ihar-$FILENAME

# Success; move to archived reports
ARCHIVES=~/reports
mkdir -p $ARCHIVES
mv $ABSNAME $ARCHIVES
